In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_colwidth',100)
df=pd.read_csv("sample_text.csv")


In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

### Creating source embeddings

In [5]:
from sentence_transformers import SentenceTransformer


C:\Users\Ilham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange


In [6]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

C:\Users\Ilham\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [7]:
vectors.shape

(8, 768)

In [8]:
vectors[0]

array([-2.47388682e-03,  3.62673365e-02, -5.29046096e-02, -2.17348877e-02,
        1.41724274e-02, -1.01590191e-03,  2.23637223e-02,  3.65196280e-02,
        3.80901434e-02,  5.22014312e-03, -3.00865453e-02,  2.05452158e-03,
        1.08502563e-02, -8.49087536e-02, -5.57267573e-03, -6.06598817e-02,
        2.32008263e-03, -1.51408855e-02,  1.20671112e-02,  1.98904984e-02,
       -1.27936248e-02, -2.72811372e-02, -3.31878886e-02,  3.40650789e-03,
        8.41175765e-03, -1.94854587e-02,  4.88132462e-02,  2.24119071e-02,
        4.53466363e-02, -5.90892173e-02, -9.13182870e-02, -1.22325413e-03,
       -4.05045599e-02,  8.67179222e-03,  1.26565305e-06, -1.92451477e-02,
       -3.20659019e-02, -4.08172496e-02,  8.79176334e-02, -1.52631244e-02,
        1.09909130e-02, -4.47978042e-02, -4.74823685e-03,  3.52632664e-02,
        1.31070921e-02,  1.09944073e-02, -3.45755927e-03,  9.12349299e-02,
        5.68808839e-02,  4.82893139e-02, -4.51440783e-03,  3.58451791e-02,
       -2.44209990e-02, -

In [9]:
dim=vectors.shape[1]
dim

768

In [10]:
import faiss

index=faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000028D2D1700C0> >

In [11]:
index.add(vectors)

### Searching in the vector Databset using query

In [25]:
search_query="An apple a day keeps the doctor away"
vec=encoder.encode(search_query)
vec.shape

(768,)

In [26]:
import numpy as np
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [27]:
svec[0]

array([ 1.77043509e-02,  7.70549551e-02, -1.25191994e-02, -1.39335927e-03,
        5.92104020e-03, -1.42678954e-02, -4.72583398e-02,  3.91950132e-03,
        4.41601388e-02,  3.09807584e-02,  9.15983692e-02,  2.02602670e-02,
       -2.16004699e-02,  1.33207869e-02, -4.14276384e-02,  4.16395292e-02,
        4.37018834e-02,  6.06421335e-03,  2.21780464e-02, -1.94715764e-02,
       -3.44189666e-02,  3.79219986e-02,  5.27904974e-03,  2.22010985e-02,
       -1.11636519e-02, -2.53350567e-02,  7.79389590e-02,  3.47346850e-02,
        1.20056318e-02, -6.52653724e-02, -4.83940728e-02, -3.03445458e-02,
       -6.99562579e-02, -2.53462177e-02,  1.78119205e-06,  1.50222732e-02,
        2.15191860e-02,  2.21124552e-02, -8.38034451e-02,  3.70954210e-03,
       -2.21118256e-02, -8.53062272e-02,  6.44918706e-04,  1.62598174e-02,
       -1.88166071e-02,  3.99217978e-02, -3.13139334e-02,  2.47449428e-02,
       -7.98749086e-03,  6.11144714e-02, -1.47846183e-02,  4.11329966e-05,
        1.20446589e-02,  

In [28]:
distances,I=index.search(svec,k=2)

In [29]:
I


array([[1, 0]], dtype=int64)

In [30]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health